let items = [{title: "Google Address Autocomplete", description: "An autocompleting address field that reduces form friction and improves user experience.", link: "https://landingpage.noahmatsell.ca/google-address-autocomplete/"},
{title: "Google Doc Embed", description: "Different techniques for embedding a Google Drive PDF on a landing page.", link: "https://landingpage.noahmatsell.ca/drive-pdf-embed/"},
{title: "Dynamic Month Insertion", description: "Insert current month to improve the relevance of landing page copy.", link: "https://landingpage.noahmatsell.ca/insert-month/"},
{title: "Dynamic Visitor Data", description: "Use Targeting Monkey to personalize page content with user location and environment.", link: "https://landingpage.noahmatsell.ca/targeting-monkey-test/"},
{title: "Show Lightbox on Load", description: "Display a lightbox on a landing page after a defined period of time.", link: "https://landingpage.noahmatsell.ca/lightbox-onload/"},
{title: "Conditional Form Field", description: "Show a hidden field if a checkbox option is selected on your form.", link: "https://landingpage.noahmatsell.ca/conditional-fields/"},
{title: "Sliding Side Menus", description: "A vertical sidebar menu that appears on button click.", link: "https://landingpage.noahmatsell.ca/sliding-side-menu/"},
{title: "Hover Effects", description: "Various hover effects and how to use them with Unbounce!", link: "https://unbouncepages.com/link-hover/"},
{title: "Back to Top Button", description: "A fading back to top button that appears as users scroll down the landing page.", link: "https://landingpage.noahmatsell.ca/back-to-top-1/"},
{title: "Show Elements Effect", description: "Show page elements with a fading animation.", link: "https://landingpage.noahmatsell.ca/slow-show/"},
{title: "Fading Navigation Bar", description: "Fade in navigation bar on scroll.", link: "https://landingpage.noahmatsell.ca/fading-navigation-bar/"},
{title: "CSS Animations", description: "Emphasize the elements on your landing page with simple, beautiful animations.", link: "https://landingpage.noahmatsell.ca/animations-1"},
{title: "Count Up Animation", description: "Animation of a number counting up...", link: "https://landingpage.noahmatsell.ca/count-up-animation/"},
{title: "Focus and Glow", description: "Add focus and glowing effet to first form field automatically.", link: "https://landingpage.noahmatsell.ca/focus-and-glow/"},
{title: "Form Field Masking", description: "Ensure standardized, valid, and consistent data is sumbitted on your landing pages", link: "https://landingpage.noahmatsell.ca/form-field-masking/"},
{title: "Typed Text Effect", description: "A cool effect that types out words or phrases dynamically on your landing page.", link: "https://commu…ow-to-create-a-typed-text-effect-in-unbounce/4481"},
{title: "On-scroll Animations", description: "Animate your page elements on-scroll.", link: "https://commu…unce.com/t/tips-scripts-on-scroll-animations/3221"},
{title: "Collapsible Page Section", description: "Create a page section that vertically collapses and expands to show and hide page content.", link: "https://commu…m/t/how-to-create-a-collapsible-page-section/4408"},
{title: "Sticky Video Widget", description: "Turns a regular video into a smaller video that follows the visitor as they scroll.", link: "https://commu…ounce.com/t/how-to-add-a-sticky-video-widget/4085"},
{title: "Mobile Hamburger Menu", description: "Create a hamburger menu for your mobile enabled pages.", link: "https://commu…ips-scripts-mobile-hamburger-navigation-menu/3289"},
{title: "Conversational Forms", description: "Breathe some life into your forms with this chat-like solution.", link: "https://commu…om/t/create-conversational-forms-in-unbounce/4988"},
{title: "Countdown Timer", description: " Create a sense of urgency with a countdown timer.", link: "https://commu…t/how-to-add-a-countdown-timer-in-unbounce/4777/1"},
{title: "Angled Page Sections", description: "A subtle way to indicate that more content exists … and prompt visitors to scroll down to find it.", link: "https://commu…ate-angled-page-sections-aka-false-bottoms/5836/1"},
{title: "Confetti Background", description: "inject a little ‘celebration’ into your post-click experience when visitors submit your form.", link: "https://commu…nimated-confetti-background-on-form-submit/5968/1"},
{title: "Custom Dropdown Menu Items", description: "Dynamically add dropdown menu items from external lists or APIs.", link: "https://landingpage.noahmatsell.ca/dynamic-dropdown-list/"},
{title: "100% Height Page Section", description: "Make your page section fullscreen--at any browser height!", link: "https://landingpage.noahmatsell.ca/full-height-section/"},
{title: "Device Sniffer", description: "Detect the visitor's device and add it to form submissions for better segmentation!", link: "https://landingpage.noahmatsell.ca/mobile-sniffing/"},
{title: "Advanced Email Validation", description: "Use Mailgun's API for more sophisticated email validation on your forms.", link: "https://landingpage.noahmatsell.ca/mailgun-email-validator/"},
{title: "Advanced Text Shadows", description: "These are some next level, beautiful text shadows.", link: "https://landingpage.noahmatsell.ca/advanced-text-shadows/"},
{title: "Auto Adjusting Date/Time", description: "Set your date/time once and have it automatically update based on the visitor's timezone.", link: "https://landingpage.noahmatsell.ca/dynamic-timezone-date/"}];

export default items;